### ISSUE TITLE
Search bar test is not visible in dark theme

### ISSUE THREAD

**Issue by Harsh3305** [HRV-Mart/HRV-Mart#25]
# Issue
In light theme, text enter by user in search bar is visible where else in dark theme, because background colour of search bar and text colour is same (i.e white) that is why, text is not visible.
# Screenshots
![image](https://user-images.githubusercontent.com/55652117/216897998-f9800874-faa5-4fde-8a13-701b0b8c33cf.png)
![image](https://user-images.githubusercontent.com/55652117/216898051-ad974195-898b-4a00-a715-4888f911c6fa.png)
![image](https://user-images.githubusercontent.com/55652117/216898067-27c7e36d-4ece-409c-9367-d229d4230e0d.png)

**Comment by Abhishek7Tech** [comment]
@Harsh3305  Hi I would like to work on this issue.

**Comment by Harsh3305** [comment]
Okay. 👍🏻

**Comment by Abhishek7Tech** [comment]
@Harsh3305  can dark theme can be added only when a user is logged in?

**Comment by Harsh3305** [comment]
No. For now, you can toggle website by changing browser default theme.
![image](https://user-images.githubusercontent.com/55652117/216907243-2a1903f6-9a91-4ce8-a3fa-5f30e063c42d.png)

**Comment by Abhishek7Tech** [comment]
@Harsh3305  You changed the browser theme, not the website theme? It works fine in Chrome.

**Comment by Abhishek7Tech** [comment]
It's an browser issue!

**Comment by Harsh3305** [comment]
@Abhishek7Tech ohh I see. For some reason, it is not working on Brave browser. This website theme depends on browser default theme. Let say if brave browser theme is dark then website theme also change to dark theme and if brave browser theme is light then website theme will change to light theme.

**Comment by Harsh3305** [comment]
> It's an browser issue!

May be.

**Comment by Abhishek7Tech** [comment]
@Harsh3305  Generally the browser theme and website themes has 2 different settings. In most of the websites user manually has to set theme to light or dark mode and it has nothing to with browser. In case you want to read browser settings of the user it will
be a security issue.

**Comment by Harsh3305** [comment]
> @Harsh3305 Generally the browser theme and website themes has 2 different settings. In most of the websites user manually has to set theme to light or dark mode and it has nothing to with browser. In case you want to read browser settings of the user it will be a security issue.

@Abhishek7Tech okay. If you want you can work on #24 issue. 
Thanks for working on this issue.
